package com.yucareux.tellus.integration.meridian;

import com.yucareux.tellus.Tellus;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.network.codec.ByteBufCodecs;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.Level;

/**
 * Tells a Meridian client that a dimension is generated by Tellus, and with which settings.
 *
 * <p>Meridian renders LODs entirely on the client, from a sampler it opens per dimension. Its own
 * worldgen sync only describes vanilla noise generators, so Tellus sends the settings itself and the
 * client builds a {@link TellusTerrainSampler} straight from them - no chunk generator required on
 * that side.
 *
 * <p>The settings travel as JSON produced by {@code EarthGeneratorSettings.CODEC}, which keeps this
 * payload independent of how the settings record happens to be shaped.
 */
public record TellusMeridianPayload(ResourceKey<Level> dimension, long seed, String settingsJson)
		implements CustomPacketPayload {

	public static final CustomPacketPayload.Type<TellusMeridianPayload> TYPE =
			new CustomPacketPayload.Type<>(Tellus.id("meridian_sync"));

	private static final int MAX_SETTINGS_JSON_BYTES = 262144;

	public static final StreamCodec<FriendlyByteBuf, TellusMeridianPayload> CODEC = StreamCodec.composite(
			ResourceLocation.STREAM_CODEC.map(
					location -> ResourceKey.create(net.minecraft.core.registries.Registries.DIMENSION, location),
					ResourceKey::location),
			TellusMeridianPayload::dimension,
			ByteBufCodecs.VAR_LONG,
			TellusMeridianPayload::seed,
			ByteBufCodecs.stringUtf8(MAX_SETTINGS_JSON_BYTES),
			TellusMeridianPayload::settingsJson,
			TellusMeridianPayload::new);

	@Override
	public CustomPacketPayload.Type<? extends CustomPacketPayload> type() {
		return TYPE;
	}
}
